mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls")),
]

polls/urls.py
from django.urls import path

from . import views


app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("register/", views.register, name="register"),
    path("login/", views.login, name='login'),
    path("logout", views.logout, name='logout'),
    path('questions/add', views.add_question, name="add_question")
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib import admin
# Create your models here.


class PollUser(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    country = models.CharField(max_length=50)

class Question(models.Model):
    author = models.ForeignKey(PollUser, on_delete=models.CASCADE, null=True, blank=True)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return "{} | {}".format(self.id, self.question_text) 

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return "{} | {} - {}".format(self.id, self.choice_text, self.votes)
    

class UserLog(models.Model):
    actions = [
        ('login', "Login Successfully"),
        ('question', "Look question list"),
        ('vote', "Vote a question"),
        ('detail', 'View single question info')
    ]

    user = models.ForeignKey(PollUser, on_delete=models.CASCADE)
    action_time = models.DateTimeField()
    action = models.CharField(choices=actions, max_length=20)

polls/views.py
#
import json

#
from django.db.models import F
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as _login, logout as _logout
from datetime import datetime

#
from .models import Choice, Question, PollUser, UserLog

def index(request):
    if request.user.is_authenticated:
        my_questions = Question.objects.filter(author__user=request.user).order_by("-pub_date")
        other_questions = Question.objects.exclude(author__user=request.user).order_by("-pub_date")
        context = {
            "my_questions": my_questions,
            "other_questions": other_questions,
            "user": request.user,
        }
        usr = PollUser.objects.get(user=request.user)
        log = UserLog(user=usr, action_time=datetime.now(), action='question')
        log.save()
        return render(request, "polls/index.html", context)
    else:
        return HttpResponseRedirect('/polls/login')

def detail(request, question_id):
    if request.user.is_authenticated:
        question = get_object_or_404(Question, pk=question_id)
        if question.author.user == request.user:
            return render(request, "polls/results.html", {"question": question, "is_author": True})
        else:
            return render(request, "polls/detail.html", {"question": question, "is_author": False})
    else:
        return HttpResponseRedirect('/polls/login')
    
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):
    print("POST DATA", request.POST)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))
    

def register(request):
    if request.method == "GET":
        return render(request, "polls/register.html", {})
    else:
        try:
            first_name = request.POST["firstname"]
            last_name = request.POST["lastname"]
            email = request.POST["email"]
            country = request.POST["country"]
            password = request.POST["password"]
            repeat_password = request.POST["repeat_password"]
        except:
            return render(request, "polls/register.html", {"error_message": "Missed Field"})        

        if password != repeat_password:
            return render(request, "polls/register.html", {"error_message": "Password not match."})        

    user = User.objects.create_user(username=email, email=email, password=password)
    user.first_name=first_name
    user.last_name = last_name
    user.save()
    
    poll_user = PollUser(user=user, country=country)
    poll_user.save()

    return  HttpResponseRedirect('/polls/login/')

def login(request):
    if request.method == "GET":
        return render(request, 'polls/login.html', {})
    else:
        try:
            email = request.POST["email"]
            password = request.POST["password"]
        except:
            return render(request, "polls/login.html", {"error_message": "Missed Field"}) 
        
    user = authenticate(username=email, password=password)
    print("USER", email, password)
    if user:
        _login(request, user)
        usr = PollUser.objects.get(user=user)
        log = UserLog(user=usr, action_time=datetime.now(), action='login')
        log.save()
        return HttpResponseRedirect('/polls/')

    else:
        return render(request, "polls/login.html", {"error_message": "Email or password is incorrect."}) 


def logout(request):
    _logout(request)
    return HttpResponseRedirect("/polls/login")


def add_question(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            return render(request, "polls/add_question.html", {})
        
        else:
            user = request.user
            puser = PollUser.objects.get(user=user)
            question_text = request.POST["question"]

            q = Question(author=puser,
                    question_text=question_text, 
                    pub_date=datetime.now()
                )
            q.save()
            return HttpResponseRedirect("/polls/" + str(q.id))


    else:
        return HttpResponseRedirect("/polls/login")    

polls/templates/polls/add_question.html
<form action="{% url 'polls:add_question' %}" method="post">
    {% csrf_token %}
    <legend><h1>Add New Question</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}    
  
    <input type="text" name="question" id="question" value="" placeholder="Question text">
    <br>
     
    <input type="submit" value="Add">
</form>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
<h1>Welcome {{user.first_name}} {{ user.last_name}}</h1>

<h2>My Questions</h2>
{% if my_questions %}
    <ul>
    {% for question in my_questions %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>You have not created any questions yet!</p>
{% endif %}
<br>
<br>
<h2>Other Questions</h2>
{% if other_questions %}
    <ul>
    {% for question in other_questions %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>There is not any external questions</p>
{% endif %}

<br>
<br>
<br>
<a href="{% url 'polls:logout' %}">logout</a>
<br>

<a href="{% url 'polls:add_question'%}">Add New Question</a>

polls/templates/polls/login.html
<form action="{% url 'polls:login' %}" method="post">
    {% csrf_token %}
    <legend><h1>Login</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}    
    
    <input type="text" name="email" id="email" value="" placeholder="Email">
    <br>
    <input type="password" name="password" id="password" value="" placeholder="Password">
    <br>
    <input type="submit" value="Login">
</form>

polls/templates/polls/register.html
<form action="{% url 'polls:register' %}" method="post">
    {% csrf_token %}
    <legend><h1>Register</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}    
  
    <input type="text" name="firstname" id="firstname" value="" placeholder="Firstname">
    <br>
    <input type="text" name="lastname" id="lastname" value="" placeholder="Last Name">
    <br>
    <input type="text" name="email" id="email" value="" placeholder="Email">
    <br>
    <input type="text" name="country" id="country" value="" placeholder="Country">
    <br>
    <input type="password" name="password" id="password" value="" placeholder="Password">
    <br>
    <input type="password" name="repeat_password" id="repeat_password" value="" placeholder="Repeat Password">
    <br> 
    <input type="submit" value="Register">
</form>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>